#! /bin/zsh

#-- scratchpad-global-toggle --#
# Helper script that toggles visibility
# of multiple scratchpad windows.
#
# Any window that is marked as sticky
# is considered as a scratchpad window.
#
# Essentially a simplified scratchpad-tiles
# script with no config file and program launching.
# Dependencies:
#	- bspwm
# ~ ADIGEN

id=`bspc query -N -n .sticky`

# Show a blurred background
if [ -f ~/.cache/scratchpad-blur.lock ]; then
	kill `cat ~/.cache/scratchpad-blur.lock`
	rm ~/.cache/scratchpad-blur.lock
	state=on
else
	(echo 'exec("""\nfrom Xlib import X, display, Xatom\ndisplay = display.Display()\nscreen = display.screen()\nwindow = screen.root.create_window(\n    0, 0, 1920, 1080, 1,\n    screen.root_depth,\n    background_pixel=screen.black_pixel\n)\nwindow.set_wm_class("blur", "blur")\nwindow.change_property(display.get_atom("_NET_WM_WINDOW_OPACITY"), Xatom.CARDINAL,32,[0x20000000])\nwindow.change_property(display.get_atom("_NET_WM_STATE"), Xatom.ATOM,32,[display.get_atom("_NET_WM_STATE_FULLSCREEN"),display.get_atom("_NET_WM_STATE_STICKY")])\nwindow.map()\nwhile True: display.next_event()\n""")' | python - & p=$!; echo $p > ~/.cache/scratchpad-blur.lock; wait $p; rm ~/.cache/scratchpad-blur.lock ) & 
	state=off
fi

while read -r instance; do
	bspc node "${instance}" --flag hidden=${state} --layer above
done <<<"${id}"
